### ISSUE TITLE
Time Step Vs Iteration Step

### ISSUE THREAD

**Issue by Puneet-G** [alecjacobson/computer-graphics-mass-spring-systems#14]
I'm a bit confused with what would be updated when iterating the Local-Global Algorithm.
As the readme states and we did in class:
1. We fix Pt, and then find d.
2. Then we fix d, and solve for P.
![image](https://user-images.githubusercontent.com/53804323/69886519-53575d80-12b0-11ea-90fc-071dfd7177bc.png)

Now from the read me, we use Pt and Pt-step to solve for Pt+step.
![image](https://user-images.githubusercontent.com/53804323/69886513-42a6e780-12b0-11ea-96b4-200c9e17a9c2.png)

If thats the case, how do we iterate again?
What value is updated when we go back to step one, as we only got a new value for Pt+step?

Have I misunderstood what we are solving for?

**Comment by s99090** [comment]
I had the same question. I believe the only value we need to update is the Pt+step. From the new value, we get a new d, and go to step 2 to find a better Pt+step. And I think Pt and Pt-step should not be changed.
I guess the current value of P in the step one is actually the Pt+step which is initialized with current Pt.

**Comment by Puneet-G** [comment]
Thanks for your response!

So if we solve for Pt+step, when we do the second(and later) iteration, we recalculate d using this p value, whereas we had been using Pt, but for step 2, we continue using the original Pt?

What would be the physics reasoning behind that?

**Comment by s99090** [comment]
Yes, for step 2, we continue using the original Pt and the new d from step 1 (from the new Pt+step).

From my understanding, the math behind this algorithm is just to find a better gradient, d, which minimizes the energy.

**Comment by abhimadan** [comment]
Slight correction: `d` is a rest spring vector, not a gradient.

We could imagine computing `d` based on our current estimate of `p` or by the previous position `p^t`, but using the latter tends to make the simulation unstable unless we use extremely small time steps. But, if we use an estimate of our next position, we are able to take larger time steps safely.

**Comment by alecjacobson** [comment]
This thread gets an important distinction. The outer most loop of the algorithm is stepping through time by increments of ∆t. t=0,t=∆t,t=2∆t, ... 

Once a specific t is chosen (as in, "alright, we'd like to see the animation at the 123th frame so the time is now t=122*∆t and will soon be 122*∆t+∆t, where are all the masses"), then we solve an optimization problem to compute p^t+∆t. Once it's computed we render those positions and repeat.


**_Within_* the optimization problem we have an inner loop. This is not a requirement of an animation system, but rather a characteristic of this particular iterative solver. Remember in lecture, we needed this loop even when solving the statics (non animating) case. The job of this inner loop is to improve the solution for this specific time step. We only render the final result (not the substeps).
