### ISSUE TITLE
How long should it takes for run the "./masssprings_dense ../data/flag.json"?

### ISSUE THREAD

**Issue by VivianZ99** [alecjacobson/computer-graphics-mass-spring-systems#16]
I successfully produced the correct results for single spring, horizontal chain and net.

However,  when I tried to run "./masssprings_dense ../data/flag.json", it took more than 5 minutes but still didn't pop up the OpenGL window, does it mean I implement the dense code wrong?

**Comment by abhimadan** [comment]
If you're not running it in release mode, then it's possible for it to take that long. The three simple examples all have less than 100 vertices, so they run reasonably even in debug mode.
