### ISSUE TITLE
Flag.json slow using sparse implementation

### ISSUE THREAD

**Issue by codr4412** [alecjacobson/computer-graphics-mass-spring-systems#20]
For the sparse matrix implementation I've used the same code I had for the dense implementation, but I've made every regular matrix (including ones from the input) into a sparse matrix using the triplet method in the readme. Despite this Flag.json still runs really slow (about 40 seconds per frame on debug, and like 5-10 seconds per frame on release).

Not sure what I'm doing wrong, any help would be appreciated!

**Comment by alecjacobson** [comment]
Just a thought, but double check that you're not adding all of the zeros to the triplet list.

5-10 secs in release mode is too slow. Was your dense code working _correctly_ on the small examples?

**Comment by codr4412** [comment]
I double checked and made sure there are no zeros by explicitly checking before pushing tuples.
My dense code looks correct on the small examples, I compared it visually with the gifs in the \images folder.
It seems that my calculation of the d matrix in the step function is what's slowing everything down. I'm currently using a for loop to calculate each entry but I'm not sure that's the best way.

**Comment by abhimadan** [comment]
Maybe I'm misunderstanding, but are you checking _every_ entry in _every_ matrix to be non-zero and only adding non-zero entries to the triplet list? Some of these matrices are very large, and checking a condition for every entry is about as expensive as writing every entry in a dense matrix, even if you don't end up writing data for most of them. The key behind the performance boost with sparse matrices is that you know which entries are non-zero / can be non-zero, and only store those as triplets. The signed incidence matrix A is a good example, as the formula explicitly tells you which entries are non-zero based on the connectivity of the springs.

**Comment by codr4412** [comment]
No, for the example you gave with matrix A, the loop that creates that matrix only runs _m_ times and pushes _2m_ entries where _m_ is the number of edges.
I think what I'm struggling with is the calculation of matrix d, I can't think of a way to vectorize it and iterating over each edge 50 times per update seems like a lot.

**Comment by abhimadan** [comment]
d is a dense matrix, so it's not really worth doing anything overly clever here. The good news is that it's a `#E * 3` matrix, so the number of entries is still roughly linear in the number of vertices.

**Comment by codr4412** [comment]
The only other thing I can think of is matrix operations, are we supposed to take the dense input matrices (like fext) and convert them to sparse matrices so we can use them in our sparse calculations?

**Comment by abhimadan** [comment]
No, if they're given as dense then you should assume that they stay dense. Sparse matrices and dense matrices can be multiplied together so you don't need to convert one to the other to work with them simultaneously.

Actually, after reading your original comment, I think this conversion is the root of your issue. In general, matrices like `Uprev` and `Ucur` are dense so it's wasteful to convert them to sparse matrices, and the matrix operations are less efficient when you try to represent a dense matrix in a sparse form.

**Comment by codr4412** [comment]
Thank you so much, that was the issue!
Just to make sure, is it okay if the debug version runs slow, but the release version runs as fast as the ones in the gifs?

**Comment by abhimadan** [comment]
Yes, that's fine
