### ISSUE TITLE
graphics.berkeley.edu link in the README seems dead?

### ISSUE THREAD

**Issue by alyssarosenzweig** [alecjacobson/computer-graphics-mass-spring-systems#25]
http://graphics.berkeley.edu/papers/Liu-FSM-2013-11/Liu-FSM-2013-11.pdf doesn't resolve for me

$ wget https://graphics.berkeley.edu/papers/Liu-FSM-2013-11/Liu-FSM-2013-11.pdf
--2022-03-21 17:08:58--  https://graphics.berkeley.edu/papers/Liu-FSM-2013-11/Liu-FSM-2013-11.pdf
Resolving graphics.berkeley.edu (graphics.berkeley.edu)... 128.32.244.183
Connecting to graphics.berkeley.edu (graphics.berkeley.edu)|128.32.244.183|:443... failed: No route to host.

**Comment by alecjacobson** [comment]
thx. fixed in b03010703d35ddc848a89728a327369b20bd4f61
