### ISSUE TITLE
Equation(22) Qp = b?

### ISSUE THREAD

**Issue by Kylinee** [alecjacobson/computer-graphics-mass-spring-systems#8]
After the Equation(22), it states "We can conceptually rewrite our system as 𝐐𝐩=𝐛 with 𝐋𝐋⊤𝐩=𝐛."
Should it be 𝐐𝐩𝑡+∆t=𝐛 with 𝐋𝐋⊤𝐩𝑡+∆t=𝐛 instead?

**Comment by alecjacobson** [comment]
technically no. p is the argument in the argmin. Once it is found then you'll set p^(t+∆t) equal to it.

( In your code you'll probably do this in a single step )

**Comment by alecjacobson** [comment]
(I'll fix my other lines to be consistent!)
